### ISSUE TITLE
Automated Email Feature Unreliable

### ISSUE THREAD

**Issue by raj88-bit** [NSFOpenData/backend#30]
Email notifications for a matching pet description are not working yet.

This is the goal. First, a person reports a missing pet via a “createPartialAnimal” .  Then, a matching description happens via the “createAnimal” call.

**Comment by salomondush** [comment]
When a match is found for an existing email, an automated email is supposed to be sent to the owner, but that's not the case currently. 

Below is the relevant piece of code in the graphql/resolvers/index.js directory

[graphql/resolvers/index.js](https://github.com/NSFOpenData/backend/blob/bf1e5033d842e4ccd4fbe61f08a5d301c47c69eb/graphql/resolvers/index.js#L68)
